version: "3.2"
services:
  graph-tool:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/user
    command: bash -c "jupyter notebook --ip 0.0.0.0 --no-browser"
    user: user
    working_dir: /home/user